### ISSUE TITLE
你好，请问ModuleNotFoundError: No module named 'transformers.modeling_gpt2'

### ISSUE THREAD

**Issue by cxncoco** [liucongg/GPT2-NewsTitle#38]
出现一下错误怎么解决呢

Traceback (most recent call last):
  File "E:\py\gpt1\generate_title.py", line 15, in <module>
    from model import GPT2LMHeadModel
  File "E:\py\gpt1\model.py", line 14, in <module>
    from transformers.modeling_gpt2 import GPT2PreTrainedModel, GPT2Model
ModuleNotFoundError: No module named 'transformers.modeling_gpt2'

**Comment by Ziba-li** [comment]
> 出现一下错误怎么解决呢
> 
> How to solve the problem if there is a mistake
> 
> Traceback (most recent call last): 追溯(最近一次通话) : File "E:\py\gpt1\generate_title.py", line 15, in 文件“ E: py gpt1 create _ title.py”，第15行，in from model import GPT2LMHeadModel 从模型导入 GPT2LMHeadModel File "E:\py\gpt1\model.py", line 14, in 文件“ E: py gpt1 model. py”，第14行，in from transformers.modeling_gpt2 import GPT2PreTrainedModel, GPT2Model Import GPT2PreTrainedModel，GPT2Model ModuleNotFoundError: No module named 'transformers.modeling_gpt2' ModuleNotFoundError: 没有名为‘ formers.model _ gpt2’的模块

transformers包已经更新了，试下 `from transformers import GPT2PreTrainedModel, GPT2Model`

**Comment by cxncoco** [comment]
好的，请问一下，从头训练一个新模型，是怎么生成新的初始化模型，还是直接用通用模型训练？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liucongg/GPT2-NewsTitle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liucongg/GPT2-NewsTitle] 你好，请问ModuleNotFoundError: No module named 'transformers.modeling_gpt2' (Issue #38)





  
出现一下错误怎么解决呢
 
How to solve the problem if there is a mistake
 
Traceback (most recent call last): 追溯(最近一次通话) : File "E:\py\gpt1\generate_title.py", line 15, in 文件“ E: py gpt1 create _ title.py”，第15行，in from model import GPT2LMHeadModel 从模型导入 GPT2LMHeadModel File "E:\py\gpt1\model.py", line 14, in 文件“ E: py gpt1 model. py”，第14行，in from transformers.modeling_gpt2 import GPT2PreTrainedModel, GPT2Model Import GPT2PreTrainedModel，GPT2Model ModuleNotFoundError: No module named 'transformers.modeling_gpt2' ModuleNotFoundError: 没有名为‘ formers.model _ gpt2’的模块
  
transformers包已经更新了，试下 from transformers import GPT2PreTrainedModel, GPT2Model

**Comment by liucongg** [comment]
transformer版本的问题
